#!/usr/bin/env zsh

# Add tab completion for SSH hostnames based on $HOME/.ssh/config, ignoring wildcards
if [ -e "$HOME/.ssh/config" ]; then
  _ssh_hosts() {
    compadd $(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2)
  }
  compdef _ssh_hosts ssh scp sftp rsync
fi
