#!/usr/bin/env bash

function updateReactEnv {
	npx react-codemod manual-bind-to-arrow $1 --force
	git commit "Remove React Component Binds"
	npx react-codemod pure-component $1 --force
	git commit "Remove React Classes"
	# npx react-codemod update-react-imports $1 --force
	# git commit "Remove React Imports"
	npx @nullvoxpopuli/optional-chaining-codemod $1 --force
	git commit "Optional Chaining"
}
