#!/usr/bin/env bash

function release {
	if [ -z "$1" ]; then
		echo "Please, suppy a branch to release";
		return;
	fi
	git switch develop && git merge $1 -m "$1" && git push;
	git switch staging && git merge $1 -m "$1" && git push;
	git switch main && git merge $1 -m "$1" && git push;
}
