#!/usr/bin/env zsh

alias update='clear; __updateCommands; __updateNPM; __updateApps; __updateDock; __updatesCleanup;'

function __updateCommands {
	brew update
	brew upgrade
}

function __updateApps {
	brew cu -qay --clean
	mas upgrade
	sudo softwareupdate -i -a
}

function __updateNPM {
	npm -g update
}

function __updateRuby {
	sudo gem update --system
	sudo gem update
	sudo gem cleanup
}

function __updatesCleanup {
	brew cleanup -s
}

function __updateDock {
	dockutil -r all \
		-a /Applications/Safari.app \
		-a /Applications/Google\ Chrome.app \
		-a /System/Applications/Mail.app \
		-a /System/Applications/Calendar.app \
		-a /Applications/Things3.app \
		-a /Applications/Visual\ Studio\ Code.app \
		-a /Applications/iTerm.app \
		-a /Applications/Whatsapp.app \
		-a /Applications/Slack.app \
		-a /System/Applications/Podcasts.app \
		-a /System/Applications/Music.app \
		-a /System/Applications/System\ Preferences.app \
		-a ~/Downloads
}
