#!/usr/bin/env zsh

timezsh() {
	shell=${1-$SHELL}
	for i in $(seq 1 10); do /usr/bin/time "$shell" -i -c exit; done
}

runsub() {
	local cmd="${1:?Usage: runsub <command>}"
	for dir in ./*(/); do
		(
			cd "$dir" || continue
			echo "Running $cmd in $dir"
			eval "$cmd"
		)
	done
}
