#!/usr/bin/env bash
# Bash Functions

# Makes cd to perform a ls
function cd {
	builtin cd "$@" && ls
}

function wpupdate {
	wp core update
	wp plugin update --all
	wp theme update --all
	wp core language update
}
