#!/usr/bin/env bash
# Bash Functions

# Makes cd to perform a ls
function cd {
	builtin cd "$@" && ls
}

function wpupdate {
	user=$(stat -c '%U' .)
	sudo -u $user wp core update
	sudo -u $user wp plugin update --all
	sudo -u $user wp theme update --all
	sudo -u $user wp core language update
}
