#!/usr/bin/env zsh

# XDG Base Directory
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"

export EDITOR="nvim"
export VISUAL="nvim"

# Add user@host to Tab Name
export PROMPT_COMMAND='echo -ne "\033]0;${USER}@$(hostname -s)\007"'

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

# Tab width: 3 spaces everywhere
tabs -3
export LESS='-x3'

# Make some commands not show up in history
export HISTORY_IGNORE="(cd|cd *|ls|ls *|l|l *|ll|ll *|la|la *|brew|brew *|j|j *|z|z *|pwd|clear|exit|__|__*|*kraken*|*rainbow*)"

# Display time in History
export HISTTIMEFORMAT='%F %T '

# Cli COLOR
export CLICOLOR=1

# Localpath
PATH="$HOME/.local/bin:$PATH"

export PATH
