#!/usr/bin/env zsh

# NI
export NI_CONFIG_FILE="$DOTFILES/config/nirc"
export COREPACK_ENABLE_AUTO_PIN=0

# Bun global packages
export PATH="$HOME/.cache/.bun/bin:$PATH"

# OpenCode
export PATH="$HOME/.opencode/bin:$PATH"
