#!/usr/bin/env zsh

# Dev Shortcuts
alias c="cursor"
alias .="cursor ."
alias c.="cursor ."
alias v="vim"
alias v.="vim ."

alias bump="nu && cam 'chore: Bump versions' && push"

alias brew=" brew"

# Node Shortcuts
alias y="ni"
alias r="nr "
alias rd="r dev"
alias rj="clear; r jest"
alias rjc="clear; r jest --collectCoverageFrom --coverage"
alias rt="clear; r test"
alias rr="clear; nlx"

# Now Shortcuts
alias deploy="vercel --prod"
