#!/usr/bin/env zsh

# Git
alias g="git"
alias add="git add"
alias cam="git cam"
alias clone="git clone"
alias gb="git branch"
alias gc="git checkout"
alias gcb="git checkout -b"
alias gd="git diff"
alias glg="git lg"
alias gs="git sz; #"
alias pull="git pull"
alias push="git push"
alias remote="git remote"
alias status="git st"
alias sync="gitup ."
alias syncall="gitup"
