#!/usr/bin/env zsh
# Git
alias g="git"
alias add="git add"
alias gb="git branch"
alias gc="git checkout"
alias gcb="git checkout -b"
alias clone="git clone"
alias cam="git commit -am"
alias gd="git diff"
alias glg="git lg"
alias pull="git pull"
alias push="git push"
alias remote="git remote"
alias status="git status -sb"
alias gmdm="gitup ."
alias sync="gitup ."
alias syncall="gitup ."
alias pr='gh pr create -f -t $(git current-branch) -a \"@me\" -B'
