#!/usr/bin/env zsh

# Git
alias g="git"
alias add="git add"
alias cam="git cam"
alias clone="git clone"
alias gb="git branch"
alias gc="git checkout"
alias gcb="git checkout -b"
alias grb="git rebase"
alias gd="git diff"
alias glg="git lg"
alias gs="git sz"
alias pull="repo_has_remote && git pull || echo 'No remote set'"
alias push="repo_has_remote && git push || echo 'No remote set'"
alias pushf="repo_has_remote && git push --force || echo 'No remote set'"
alias pp='git pull && git push'
alias remote="git remote"
alias status="git st 2>/dev/null"
alias cdgr='cd $(git root)'
alias sync="cdgr && gitup ."
alias syncall="gitup"
alias lg="lazygit"

# Projects
alias grm='git rebase $(git mb)'
alias grom='git rebase -X ours $(git mb)'
alias grtm='git rebase -X theirs $(git mb)'
alias gmm='git merge $(git mb)'
alias gma='git merge --abort'
alias gmc='git merge --continue'
alias gra='git rebase --abort'
alias grc='git rebase --continue'

# Pruning local branches no longer needed
alias clb='sync && git clb'

# PRs
alias pr='gh pr create -f -t $(git current-branch) -a \"@me\" -B'
alias prm='push && pr $(git mb)'
alias prdev='pr develop'
alias prstg='pr staging'

# Gitlab PRs
alias glpr='gl mr create -t $(git current-branch) -f --fill-commit-body -y -a \"@me\" -b'
alias glprm='push && glpr $(git mb)'
alias glprd='glpr develop'
alias glprs='glpr staging'

# Git remotes
alias grhttps='git remote set-url origin $(git remote get-url origin | sed -E "s|git@([^:]+):(.*)|https://\1/\2|")'
alias grssh='git remote set-url origin $(git remote get-url origin | sed -E "s|https://([^:]+)/(.*)|git@\1:\2|")'
