#!/usr/bin/env zsh

# List all files colorized in long format, including dot files

# Detect which `ls` flavor is in use
if ls --group-directories-first >/dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
	directoriesflag="--group-directories-first"
	lsbin="$(command -v ls)"
else # macOS `ls`
	colorflag="-G"
	directoriesflag=""
	lsbin="ls"
fi

alias j="z"

# List all files colorized in long format
alias ls="clear; ${lsbin} ${colorflag} ${directoriesflag}"
alias l="ls"
alias lsa="ls -A"
alias ll="ls -hl"
alias lla="ll -A"
alias lsd="${lsbin} -lF ${colorflag} ${directoriesflag} | grep --color=never '^d'"
alias pwdl="ls; echo; pwd"

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias h="cd ~"
alias -- -="cd -"

# Main folder Navigation
alias d="cd $HOME/Desktop"
alias p="cd $HOME/Developer/Proyectos"
alias w="cd $HOME/Developer/Work"
alias dot="cd $DOTFILES"
