#!/bin/bash
# List all files colorized in long format, including dot files
alias ls="clear && ls -G"
alias l="ls"
alias lsa="ls -A"
alias ll="ls -hl"
alias lla="ll -A"
alias lsd='ls -l | grep "^d"'

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias h="cd ~"
alias -- -="cd -"

# Main folder Navigation
alias d="cd ~/Desktop"
alias p="cd ~/Developer"
alias db="cd ~/Dropbox"
alias si="cd ~/Sites"
alias dot="cd ~/.config/dotfiles"
