video=no
audio-display=no
audio-device=alsa/plughw:CARD=Headphones,DEV=0
ytdl-format=bestaudio/best
script-opts=ytdl_hook-ytdl_path=/usr/local/bin/yt-dlp
ytdl-raw-options=js-runtimes=quickjs
cache=yes
cache-secs=15
