#!/usr/bin/env zsh

alias update='clear; __updateCommands; __updateNPM; __updateBenchmark;'

function __updateCommands {
	if command -v apt &>/dev/null; then
		sudo apt update && sudo apt upgrade -y
	elif command -v dnf &>/dev/null; then
		sudo dnf upgrade -y
	elif command -v pacman &>/dev/null; then
		sudo pacman -Syu --noconfirm
	fi

	# Linuxbrew if installed
	if command -v brew &>/dev/null; then
		brew update && brew upgrade
	fi
}

function __updateNPM {
	bun update -g
}

function __updateBenchmark {
	echo "Shell startup benchmark:"
	timezsh
}
