#!/usr/bin/env bash
# Make nano the default editor
export EDITOR="nano"

# Add user@host to Tab Name
export PROMPT_COMMAND='echo -ne "\033]0;${USER}@$(hostname -s)\007"'

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# History Management
export HISTCONTROL=ignoredups
# Make some commands not show up in history
export HISTIGNORE="clear"

# Display time in History
export HISTTIMEFORMAT='%F %T '

# Set Node.js Path
export NODE_PATH=/usr/local/opt/node@12/bin
export PATH="$PATH:$NODE_PATH"
# export NPM_PACKAGES=$HOME/.npm-packages
# export NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"
# export PATH="$NPM_PACKAGES/bin:$PATH"

# Set Ruby Path
export RUBY_PATH=/usr/local/lib/ruby/gems/2.7.0
export PATH="$RUBY_PATH/bin:$PATH"

# Set Composer Path
export COMPOSER_PATH=$HOME/.composer/vendor/bin
export PATH="$COMPOSER_PATH:$PATH"
