# Path
export PATH=$HOME/.local/bin:/usr/local/bin:$PATH

# History configuration
HISTSIZE=50000
SAVEHIST=50000
HISTFILE=~/.zsh_history
setopt HIST_IGNORE_ALL_DUPS  # Remove older duplicates
setopt HIST_IGNORE_SPACE     # Ignore commands starting with space
setopt HIST_NO_FUNCTIONS     # Don't save functions
setopt HIST_REDUCE_BLANKS    # Remove superfluous blanks
setopt SHARE_HISTORY         # Share history between sessions
setopt AUTO_CD               # cd by typing directory name
setopt INTERACTIVE_COMMENTS  # Allow comments in interactive shell

# Filter commands from history (uses HISTORY_IGNORE from exports)
zshaddhistory() {
  emulate -L zsh
  [[ $1 != ${~HISTORY_IGNORE} ]]
}

# Completion settings
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'  # Case insensitive
zstyle ':completion:*' menu select                       # Menu selection
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" # Colored completions
autoload -Uz compinit && compinit

# Zinit plugin manager
ZINIT_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/zinit/zinit.git"
if [[ ! -d $ZINIT_HOME ]]; then
  mkdir -p "$(dirname $ZINIT_HOME)"
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi
source "${ZINIT_HOME}/zinit.zsh"

# Plugins (turbo mode for fast startup)
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light Aloxaf/fzf-tab

# Snippets (oh-my-zsh plugins without oh-my-zsh)
zinit snippet OMZP::git
zinit snippet OMZP::macos
zinit snippet OMZP::brew
zinit snippet OMZP::npm
zinit snippet OMZP::node
zinit snippet OMZP::gh

# Tool integrations
eval "$(fzf --zsh)"
eval "$(zoxide init zsh)"

# User configuration
source $HOME/.profile

# Prompt (similar to edvardm theme)
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats ' %F{magenta}(%b)%f'
setopt PROMPT_SUBST
PROMPT='%F{green}%~%f${vcs_info_msg_0_} %F{yellow}❯%f '
