#!/bin/sh

STAGED_FILES=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# check for php
which php &> /dev/null
if [[ "$?" == 1 ]]; then
	echo "\033[41mPlease install PHP.\033[0m"
	exit 1
fi

PASS=true

#PHPLint
echo "Checking PHP Lint...\n"

for FILE in $STAGED_FILES
do
	php -l -d display_errors=0 "$FILE"
	if [[ "$?" != 0 ]]; then
		echo "\033[41mPHPLint Failed: $FILE\033[0m"
		PASS=false
	fi
	FILES="$FILES $FILE"
done

if ! $PASS; then
	echo "\n\033[41mPHPLint Failed. Fix the errors and try again.\033[0m"
	exit 1
fi

echo "Checking PHP Lint Completed!\n"

exit $?
