tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "lotyp/formulae"
tap "oven-sh/bun"
tap "smudge/smudge"
tap "yt-dlp/taps"
tap "zackelia/formulae"
brew "asimov", restart_service: :changed
brew "atomicparsley"
brew "bat"
brew "cmake"
brew "coreutils"
brew "docker", link: false
brew "fx"
brew "fzf"
brew "git-delta"
brew "starship"
brew "gh"
brew "git"
brew "gitui"
brew "gitup"
brew "httpie", link: false
brew "imagemagick"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "libusb"
brew "lotyp/formulae/dockutil"
brew "mackup"
brew "mas"
brew "musikcube"
brew "neovim"
brew "node@20", link: true
brew "openldap"
brew "oven-sh/bun/bun"
brew "pwgen"
brew "reattach-to-user-namespace"
brew "rename"
brew "ruby"
brew "smudge/smudge/nightlight"
brew "ssh-copy-id"
brew "tldr"
brew "tmux"
brew "tree"
brew "uni2ascii"
brew "uv"
brew "watchman"
brew "wget"
brew "wifi-password"
brew "yq"
brew "yt-dlp"
brew "zackelia/formulae/bclm"
cask "adobe-acrobat-reader"
cask "aerial"
cask "arc"
cask "audacity"
cask "autofirma"
cask "battle-net"
cask "caffeine"
cask "camo-studio"
cask "cursor"
cask "dbngin"
cask "discord"
cask "docker-desktop"
cask "font-geist-mono"
cask "font-ia-writer-duo"
cask "font-ia-writer-mono"
cask "font-ia-writer-quattro"
cask "font-jetbrains-mono"
cask "ghostty"
cask "handbrake-app"
cask "httpie-desktop"
cask "jdownloader"
cask "kapitainsky-rclone-browser"
cask "karabiner-elements"
cask "keyboardcleantool"
cask "kid3"
cask "logitech-options"
cask "netnewswire"
cask "notion"
cask "obs"
cask "obs-websocket"
cask "obsidian"
cask "openmtp"
cask "oracle-jdk"
cask "postman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "raycast"
cask "scummvm-app"
cask "slack"
cask "sony-ps-remote-play"
cask "syncthing-app"
cask "tableplus"
cask "the-unarchiver"
cask "transmission"
cask "transmit"
cask "via"
cask "visual-studio-code"
cask "vlc"
mas "Actions", id: 1586435171
mas "AdGuard for Safari", id: 1440147259
mas "Artifacts", id: 0
mas "Consent-O-Matic", id: 1606897889
mas "Data Jar", id: 1453273600
mas "Developer", id: 640199958
mas "Flighty", id: 1358823008
mas "Hush", id: 1544743900
mas "Hyperduck", id: 6444667067
mas "LocalSend", id: 1661733229
mas "Minimal Twitter", id: 1668204600
mas "Parcel", id: 639968404
mas "Quick Draft", id: 1496067471
mas "Raycast Companion", id: 6738274497
mas "Refined GitHub", id: 1519867270
mas "Sink It", id: 6449873635
mas "Supercopy", id: 6477720316
mas "Synctrain", id: 6553985316
mas "Telegram", id: 747648890
mas "TestFlight", id: 899247664
mas "Things", id: 904280696
mas "Userscripts", id: 1463298887
mas "Velja", id: 1607635845
mas "WhatsApp", id: 310633997
mas "WireGuard", id: 1451685025
