#!/usr/bin/env zsh

export EDITOR="vim"

# Add user@host to Tab Name
export PROMPT_COMMAND='echo -ne "\033]0;${USER}@$(hostname -s)\007"'

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Make some commands not show up in history
export HISTORY_IGNORE="(cd|cd *|ls|ls *|l|l *|ll|ll *|la|la *|brew|brew *|j|j *|z|z *|pwd|clear|exit|__|__*|*kraken*|*rainbow*)"

# Display time in History
export HISTTIMEFORMAT='%F %T '

# Cli COLOR
export CLICOLOR=1

# Coreutils
PATH="$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin:$PATH"

# Localpath
PATH="$HOME/.local/bin:$PATH"
