#!/usr/bin/env zsh

export EDITOR="vim"

# Add user@host to Tab Name
export PROMPT_COMMAND='echo -ne "\033]0;${USER}@$(hostname -s)\007"'

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Make some commands not show up in history
export HISTORY_IGNORE="(__*|*kraken*|*rainbow*|brew|cat|cd|chmod|clear|echo|j|l*|pwd|rm|status|update)"

# Display time in History
export HISTTIMEFORMAT='%F %T '

# Cli COLOR
export CLICOLOR=1
