#!/usr/bin/env zsh

# Set Node.js Path
export NODE_PATH=/usr/local/opt/node@16/bin
export PATH="$PATH:$NODE_PATH"
# export NPM_PACKAGES=$HOME/.npm-packages
# export NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"
# export PATH="$NPM_PACKAGES/bin:$PATH"

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end
