#!/usr/bin/env zsh

# Bun setup

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end

# NI
export NI_CONFIG_FILE="$DOTFILES/config/nirc"
export COREPACK_ENABLE_AUTO_PIN=0

# Bun global packages
export PATH="$HOME/.cache/.bun/bin:$PATH"

# OpenCode
export PATH="$HOME/.opencode/bin:$PATH"
